### ISSUE TITLE
not bundle with webpack (lost control.service.d.ts)

### ISSUE THREAD

**Issue by aMoRRoMa** [formly-js/ng2-formly#18] opened 2016-04-26 09:52 UTC
[default] /Users/roma/git/sos_manager_front/node_modules/ng2-formly/src/components/formly.form.d.ts (3,32):
    Cannot find module './../services/control.service'.
[default] /Users/roma/git/sos_manager_front/node_modules/ng2-formly/src/main.d.ts (4,32):
    Cannot find module './services/control.service'.
[default] /Users/roma/git/sos_manager_front/node_modules/ng2-formly/src/services/formly.providers.d.ts (1,32):
    Cannot find module './control.service'.

**Comment by brutalcrozt** [comment] 2016-04-30 13:58
Hello @aMoRRoMa , thanks for your issue. Somehow i don't use angular 2 yet, maybe @mohammedzamakhan can give some clear point.

**Comment by divyakumarjain** [comment] 2016-05-16 22:05
is this duplicate of #32

**Closed** 2016-05-17 01:04 UTC
