### ISSUE TITLE
Run time error while running to the device

### ISSUE THREAD

**Issue by hariharan614** [formly-js/ng2-formly#239] opened 2016-11-09 12:36 UTC
Hi, 
I tried it, It works perfectly while I run in ionic lab. But when execute run to my android device, it shows an error:

Uncaught Error: Cannot find module "../node_modules/ng2-formly/lib/core/components/formly.group.ngfactory", http://*.*.*.*/build/main.js, Line: 25

Please can you help me with this?

**Comment by aitboudad** [comment] 2016-11-09 14:08
fixed by #240

**Comment by hariharan614** [comment] 2016-11-10 05:42
I'm still facing the same problem

**Comment by aitboudad** [comment] 2016-11-10 07:34
Could you provide a plunkr or a repo reproducing the problem?

**Comment by mohammedzamakhan** [comment] 2016-11-10 10:28
May be you are using beta.11. You will have to wait for this project to be tagged and pushed to npm. Or else you can also you the github latest instead

**Comment by hariharan614** [comment] 2016-11-12 06:09
Thanks for your efforts, some of the previous errors are not occuring, but now this is the only error that I'm getting. I'm using it in Ionic2. Please help me... @mohammedzamakhan @aitboudad 

[11:23:48]  Error: Error at H:/ws/formtest/.tmp/node_modules/ng2-formly/lib/ui-bootstrap/types/input.ngfactory.ts:91:35
[11:23:48]  Module ''*'' has no exported member 'Wrapper_FormlyAttributes'.
[11:23:48]  Error at H:/ws/formtest/.tmp/node_modules/ng2-formly/lib/ui-bootstrap/types/checkbox.ngfactory.ts:155:34
[11:23:48]  Module ''*'' has no exported member 'Wrapper_FormlyAttributes'.
[11:23:48]  Error at H:/ws/formtest/.tmp/node_modules/ng2-formly/lib/ui-bootstrap/types/radio.ngfactory.ts:222:35
[11:23:48]  Module ''*'' has no exported member 'Wrapper_FormlyAttributes'.
[11:23:48]  Error at H:/ws/formtest/.tmp/node_modules/ng2-formly/lib/ui-bootstrap/types/select.ngfactory.ts:94:34
[11:23:48]  Module ''*'' has no exported member 'Wrapper_FormlyAttributes'.
[11:23:48]  Error at H:/ws/formtest/.tmp/node_modules/ng2-formly/lib/ui-bootstrap/types/textarea.ngfactory.ts:86:34
[11:23:48]  Module ''*'' has no exported member 'Wrapper_FormlyAttributes'.
[11:23:48]  Error at
            H:/ws/formtest/.tmp/node_modules/ng2-formly/lib/ui-bootstrap/types/multicheckbox.ngfactory.ts:136:34
[11:23:48]  Module ''*'' has no exported member 'Wrapper_FormlyAttributes'.
[11:23:48]  ngc failed
[11:23:48]  ionic-app-script task: "build"
[11:23:48]  Error: Error

**Comment by hariharan614** [comment] 2016-11-12 07:51
![1](https://cloud.githubusercontent.com/assets/23353872/20236427/e3f518de-a8da-11e6-9633-a615c39d746f.PNG)

**Comment by hariharan614** [comment] 2016-11-12 09:58
And import of 'formly.attribute' is missing from code.d.ts. 
import { FormlyAttributes } from './components/formly.attributes';

**Comment by aitboudad** [comment] 2016-11-12 10:21
I did a try again but doesn't happen to me, as I mentioned above it would be helpful if you can provide me a repo reproducing the problem, thanks

**Comment by hariharan614** [comment] 2016-11-12 10:47
Please have a look at the src files that I have uploaded. And if you want me to upload the whole project file, I can do that. Please let me know thanks.

https://github.com/hariharan614/formlyTest.git

**Comment by aitboudad** [comment] 2016-11-12 11:02
just checked and #240 seems fixed the issue, @mohammedzamakhan can you made a new release

**Comment by hariharan614** [comment] 2016-11-12 11:11
If its available soon, it would solve my whole problem. Or if you can tell me if there I can make changes to resolve the problem by using npm, pls let me know.

**Comment by mohammedzamakhan** [comment] 2016-11-12 13:22
@aitboudad released 2.0.0-beta.12 version 🔥

**Comment by hariharan614** [comment] 2016-11-12 13:23
Thank you soo much for your support 👍 ... I'm going to try it now...

**Comment by mohammedzamakhan** [comment] 2016-11-12 13:30
@hariharan614 since you are working on ionic 2, can you help us maintain the ng2-formly-ionic-templates? 

We have one for bootstrap in this repo, and we plan to separate it out, and we have one for material 2 at https://github.com/formly-js/ng2-formly-template-material

**Comment by hariharan614** [comment] 2016-11-12 13:33
Sure, I'm happy for the opportunity. I'll look into the repo and try my best to help... 👍

**Comment by hariharan614** [comment] 2016-11-12 14:41
@mohammedzamakhan @aitboudad 

One more problem in the released version... 

![q](https://cloud.githubusercontent.com/assets/23353872/20238543/21c0305c-a914-11e6-8745-49e172929775.PNG)

**Comment by aitboudad** [comment] 2016-11-13 09:37
@mohammedzamakhan the `lib` folder isn't included in the last build

**Comment by aitboudad** [comment] 2016-11-13 09:44
see #251

**Comment by hariharan614** [comment] 2016-11-14 04:34
Hi, pls let me know about this bug fix. thank you. @aitboudad @mohammedzamakhan

**Comment by mohammedzamakhan** [comment] 2016-11-14 15:27
Try upgrading to v2.0.0-beta.13

**Closed** 2016-11-20 10:28 UTC
Labels: bug
