### ISSUE TITLE
repeated section produces errors

### ISSUE THREAD

**Issue by franzeal** [formly-js/ng2-formly#303] opened 2016-12-01 18:39 UTC
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
The repeatSection produces ExpressionChangedAfterItHasBeenCheckedError errors.

**Expected behavior**
The repeatSection should not produce ExpressionChangedAfterItHasBeenCheckedError errors when initializing or modifying its array model.

**Minimal reproduction of the problem with instructions**
This plunker is a minimal example of the issue using the current unreleased build of formly.
https://plnkr.co/edit/GblGry5mEMwhCnP3lYf8?p=preview

**Comment by mohammedzamakhan** [comment] 2016-12-01 18:43
duplicate of #270

**Closed by mohammedzamakhan** 2016-12-01 18:43 UTC
